ff00174a78447c719d106f6bf2280ae5abb5cfc7

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -11,9 +11,9 @@ jobs:
       matrix:
         ruby:
           - '2.7'
-          - '3.0'
-          - '3.1'
-          - '3.2'
+#          - '3.0'
+#          - '3.1'
+#          - '3.2'
         task:
           - spec
     steps:
@@ -29,29 +29,29 @@ jobs:
 
     - name: Run ${{ matrix.task }} on Ruby ${{ matrix.ruby }}
       run: bundle exec rake ${{ matrix.task }}
-  linters:
-    name: linters
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        ruby:
-          - 2.7
-        task:
-          - brakeman
-          - flay
-          - rubocop
-    steps:
-    - uses: zendesk/checkout@v3
-    - uses: zendesk/setup-ruby@v1
-      with:
-        ruby-version: ${{ matrix.ruby }}
-
-    - name: Gem install
-      run: |
-        set -eu -o pipefail
-        bundle install
-        bundle update brakeman flay rubocop
-
-    - name: Run ${{ matrix.task }} on Ruby ${{ matrix.ruby }}
-      run: bundle exec rake ${{ matrix.task }}
+#  linters:
+#    name: linters
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        ruby:
+#          - 2.7
+#        task:
+#          - brakeman
+#          - flay
+#          - rubocop
+#    steps:
+#    - uses: zendesk/checkout@v3
+#    - uses: zendesk/setup-ruby@v1
+#      with:
+#        ruby-version: ${{ matrix.ruby }}
+#
+#    - name: Gem install
+#      run: |
+#        set -eu -o pipefail
+#        bundle install
+#        bundle update brakeman flay rubocop
+#
+#    - name: Run ${{ matrix.task }} on Ruby ${{ matrix.ruby }}
+#      run: bundle exec rake ${{ matrix.task }}
diff --git a/.github/workflows/security.yml b/.github/workflows/security.yml
--- a/.github/workflows/security.yml
+++ b/.github/workflows/security.yml
@@ -1,37 +1,37 @@
-name: Security
-on: [push]
-jobs:
-  main:
-    name: bundle-audit
-    runs-on: ubuntu-latest
-    env:
-      RAILS_ENV: test
-    strategy:
-      fail-fast: false
-      matrix:
-        ruby:
-          - 2.7
-    steps:
-    - uses: zendesk/checkout@v3
-    - uses: zendesk/setup-ruby@v1
-      with:
-        ruby-version: ${{ matrix.ruby }}
-
-    - name: Gem install
-      run: |
-        set -eu -o pipefail
-        gem install bundler-audit
-
-    - name: Checking ${{ matrix.gemfile }}
-      run: |
-        set -eu -o pipefail
-
-        echo "BUNDLE_GEMFILE=$GITHUB_WORKSPACE/${{ matrix.gemfile }}" >> $GITHUB_ENV
-
-        IGNORED="CVE-2020-26247 GHSA-7rrm-v45f-jp64"
-
-        if [ -n "$IGNORED" ]; then
-          echo "::warning:: Ignored vulnerabilities: $IGNORED"
-        fi
-
-        bundle-audit check --update --gemfile-lock Gemfile.lock --ignore $IGNORED
+#name: Security
+#on: [push]
+#jobs:
+#  main:
+#    name: bundle-audit
+#    runs-on: ubuntu-latest
+#    env:
+#      RAILS_ENV: test
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        ruby:
+#          - 2.7
+#    steps:
+#    - uses: zendesk/checkout@v3
+#    - uses: zendesk/setup-ruby@v1
+#      with:
+#        ruby-version: ${{ matrix.ruby }}
+#
+#    - name: Gem install
+#      run: |
+#        set -eu -o pipefail
+#        gem install bundler-audit
+#
+#    - name: Checking ${{ matrix.gemfile }}
+#      run: |
+#        set -eu -o pipefail
+#
+#        echo "BUNDLE_GEMFILE=$GITHUB_WORKSPACE/${{ matrix.gemfile }}" >> $GITHUB_ENV
+#
+#        IGNORED="CVE-2020-26247 GHSA-7rrm-v45f-jp64"
+#
+#        if [ -n "$IGNORED" ]; then
+#          echo "::warning:: Ignored vulnerabilities: $IGNORED"
+#        fi
+#
+#        bundle-audit check --update --gemfile-lock Gemfile.lock --ignore $IGNORED
